const data = [
  {
    title: "Adrienne NGOTAMACK",
    id: 1,
    prooductCount: 34,
    shippingCountries: ["Cameroon", "Nigeria", "Ghana"],
    img: "/images/agents/adrienne-ngotamack.jpeg",
    description: "Spécialisée en électronique et gadgets technologiques. Fournit des produits innovants et de haute qualité. Service client exceptionnel et livraison rapide.",
  },
  {
    title: "Bosey Arthur",
    id: 2,
    prooductCount: 12,
    shippingCountries: ["Cameroon", "Ivory Coast"],
    img: "/images/agents/bosey-arthur.jpeg",
    description: "Expert en mode et accessoires. Offre une large gamme de vêtements tendance et d'accessoires uniques. Engagement envers la satisfaction client et des prix compétitifs.",
  },
  {
    title: "Carine MELONG",
    id: 3,
    prooductCount: 27,
    shippingCountries: ["Cameroon", "Senegal", "Mali"],
    img: "/images/agents/carine-melong.jpeg",
    description: "Fournisseur de produits de beauté et de soins personnels. Propose des articles de marques renommées ainsi que des produits naturels. Conseils personnalisés et promotions régulières.",
  },
  {
    title: "Esther MAFFOUO",
    id: 4,
    prooductCount: 19,
    shippingCountries: ["Cameroon", "Benin", "Togo"],
    img: "/images/agents/esther-maffouo.jpeg",
    description: "Distributeur de produits pour la maison et le jardin. Offre une variété d'articles pour améliorer le confort et l'esthétique de votre espace de vie. Livraison fiable et service après-vente dédié.",
  },
  {
    title: "Eva FONGANG",
    id: 5,
    prooductCount: 23,
    shippingCountries: ["Cameroon", "Gabon", "Equatorial Guinea"],
    img: "/images/agents/eva-fongang.jpeg",
    description: "Spécialiste en articles de sport et équipements de fitness. Propose des produits de haute performance pour tous les niveaux d'activité physique. Conseils d'experts et offres exclusives pour les clients fidèles.",
  },
  {
    title: "Marthe SAAH",
    id: 6,
    prooductCount: 15,
    shippingCountries: ["Cameroon", "Chad", "Central African Republic"],
    img: "/images/agents/marthe-saah.jpeg",
    description: "Vendeuse de produits alimentaires et boissons. Offre une sélection variée de produits frais, bio et importés. Engagement envers la qualité et la satisfaction client.",
  },
  {
    title: "Prosper Ndadjip",
    id: 7,
    prooductCount: 20,
    shippingCountries: ["Cameroon", "Liberia", "Sierra Leone"],
    img: "/images/agents/prosper-ndadjip.jpeg",
    description: "Agent en matériel électronique et informatique. Fournit des produits de marques reconnues à des prix compétitifs. Support technique et conseils personnalisés pour les clients professionnels.",
  },
  {
    title: "Raman AMIDOU",
    id: 8,
    prooductCount: 24,
    shippingCountries: ["Cameroon", "Sudan", "Ethiopia"],
    img: "/images/agents/raman-amidou.jpeg",
    description: "Distributeur de jouets et articles pour enfants. Propose une large gamme de produits sûrs et éducatifs pour les enfants de tous âges. Promotions spéciales et service client attentif.",
  },
  {
    title: "Suzanne RAMARARA",
    id: 9,
    prooductCount: 21,
    shippingCountries: ["Cameroon", "Rwanda", "Burundi"],
    img: "/images/agents/suzanne-ramarara.jpeg",
    description: "Fournisseur de meubles et décorations d'intérieur. Offre des articles de qualité pour embellir votre maison ou bureau. Conseils en design et options de personnalisation disponibles.",
  },
  {
    title: "Ulrich DJOUADA",
    id: 10,
    prooductCount: 21,
    shippingCountries: ["Cameroon", "Angola", "Namibia"],
    img: "/images/agents/ulrich-djouada.jpeg",
    description: "Spécialiste en équipements industriels et outils professionnels. Propose des produits robustes et fiables pour divers secteurs d'activité. Service client dédié et solutions sur mesure pour les entreprises.",
  },
  {
    title: "Estelle NAYA",
    id: 11,
    prooductCount: 21,
    shippingCountries: ["Cameroon", "South Africa", "Zimbabwe"],
    img: "/images/agents/estelle-naya.jpeg",
    description: "Vendeuse de produits artisanaux et faits main. Offre une sélection unique d'articles créés par des artisans locaux. Soutien à l'artisanat et engagement envers le commerce équitable.",
  }
];

export default data;
